### ISSUE TITLE
Man command output incomplete

### ISSUE THREAD

**Issue by xeruf** [AndrewRadev/bufferize.vim#7] opened 2020-04-05 20:56 UTC
I wanted to use Bufferize to display a manpage alonside my file, so I installed it and ran

    :Bufferize !man sudoers

But after messing around a little I discovered that the man page was somehow shortened - only 285 lines instead of 1696, which it has when I execute the same command outside of vim.

**Comment by AndrewRadev** [comment] 2020-04-06 18:51
Interesting problem. To be honest, I'm having a hard time replicating the situation -- for me, running `:!man sudoers` runs man with a pager, and when I quit out of it, no output is produced. What operating system are you using? Could you also let me know if you have anything set for the `$MANPAGER` environment variable?

As an aside, you could get man output in Vim by using its built-in support: [`:help :Man`](https://vimhelp.org/filetype.txt.html#%3AMan). So, with the `ftplugin/man.vim` runtime'd, you could execute `:Man sudoers` to get the contents in a syntax-highlighted buffer. Of course, I'd still like to figure out what the issue is for the truncated content, but this could help you out with your particular problem at least :).

**Comment by xeruf** [comment] 2020-04-07 08:05
Thanks for the tip :)

Yes, `:!man sudoers` indeed runs through a pager, that is exactly why I stumbled upon your plugin. `:Bufferize !man sudoers` puts it into a Buffer, which is great, but it seems to truncate the result in the middle - see the saved output below:

[Bufferize-man-sudoers.txt](https://github.com/AndrewRadev/bufferize.vim/files/4442743/Bufferize-man-sudoers.txt)
[man-sudoers.txt](https://github.com/AndrewRadev/bufferize.vim/files/4442744/man-sudoers.txt)

**Comment by xeruf** [comment] 2020-04-07 08:15
Thank you very much, `:Man` is exactly what I was looking for! I will of course still assist you with this issue if anything is unclear ;)

**Comment by AndrewRadev** [comment] 2020-04-07 09:51
Ah, interesting, yes, the middle of the output is the key part:

```
         env_keep += "BASH_FUNC_my_func%%=()*"

     Without the “=()*” suffix, this would not match, as bash shell functions
     are not preserved by default.

.  
.. 
...
   
.  
.. 
...
   
.  
.. 
...
   
.  
.. 
...
   
.  
.. 
...
...
.  
.. 
...
   
.  
.. 
...
   
.  
.. 
...
   
.  
..  the boot time is available.

     Some systems with graphical desktop environments allow unprivileged users
     to change the system clock.  Since sudoers relies on the system clock for
```

There's a bunch of newlines and dots, which I feel like is maybe a result of the pager? So it truncates the content in the middle because the pager ends up sort of printing thing weirdly when it's not dumped in an interactive stdout. Maybe.

I feel like there's not much I can do in this kind of situation, because it's something that happens from the executable itself (if I'm right about it). So I don't think Vim ends up truncating the content. I don't think there's anything on the plugin's end that can be done to tell it to *not* use a pager.

For now, I'll close the issue. If anybody runs into similar truncation with non-paged output, I might reopen.

**Closed as completed** 2020-04-11 09:44 UTC

**Comment by xeruf** [comment] 2020-04-14 13:21
I don't think it happens from the executable itself actually, if you run this in a terminal no pager is used, but running it through bufferize still produces the previously mentioned truncation.
```
man -P cat sudoers
```

**Comment by xeruf** [comment] 2020-04-14 13:26
From a comment on [this SO answer](https://unix.stackexchange.com/a/23402/272449) it seems related to how vim paginates stuff.

**Comment by AndrewRadev** [comment] 2020-04-21 17:08
Frustratingly, I still can't quite replicate it. Running it as an external command gives me this:
![bufferize_demo](https://user-images.githubusercontent.com/124255/79892877-dc139900-840b-11ea-843d-db855ce54330.gif)

This happens with any external command, it seems, at least for me.

**Comment by xeruf** [comment] 2020-04-21 18:37
oh, I use neovim, that might make a difference in this edge case

**Comment by AndrewRadev** [comment] 2020-04-22 08:02
Yes, Neovim does seem to produce output in this case. And you're right, it doesn't seem to be a pager issue. I guess it's an issue with executing external commands somehow, since this seems to produce the right amount of lines:

``` vim
Bufferize echo join(readfile('man_output.txt'), "\n")
```

This does, however, give me a pretty reasonable solution, I think:

``` vim
Bufferize echo join(systemlist("man sudoers"), "\n")
```

This doesn't even need a pager, because the program can figure it out. I've added the command `:BufferizeSystem` that packages the external command in a `system()` call.

**Comment by xeruf** [comment] 2020-04-23 15:12
Thank you very much, works perfectly :)
